rem @echo off


rem Set the build directory if it is not already defined
if not defined KL_DEV_DIR (
    set KL_DEV_DIR=C:\dev
)
  
rem Set the build directory if it is not already defined
if not defined KEVERNALS_SRC_DIR (
    set KEVERNALS_SRC_DIR=%KL_DEV_DIR%\ADAM\source\personal\Kevernals\source
)

rem Root directory for finding external dependencies located in ADAM externals
if not defined ADAM_EXTERNALS_DIR (
    set ADAM_EXTERNALS_DIR=%KL_DEV_DIR%\ADAM-externals
)

rem Root directory for finding external libraries dependencies 
if not defined EXTERNALS_DIR (
    set EXTERNALS_DIR=%UserProfile%\Documents\libraries
)

rem Set the build directory if it is not already defined
if not defined KEVERNALS_BUILD_DIR (
    set KEVERNALS_BUILD_DIR=%KL_DEV_DIR%\Kevernals-build
)

if not defined DICOMCONNECT_ROOT (
	set DICOMCONNECT_ROOT=%ADAM_EXTERNALS_DIR%\DICOMconnect-3.3.3
)

if not defined Qt5_DIR (
	set Qt5_DIR=%ADAM_EXTERNALS_DIR%\Qt-5.15.8\5.15.8\msvc2019_64
)

if not defined VTK_DIR (
	set VTK_DIR=%EXTERNALS_DIR%\binaries\VTK-9.0.1
)
	
if not defined GDCM_DIR (
	set GDCM_DIR=%EXTERNALS_DIR%\binaries\gdcm-3.0.8
)

if not defined EIGEN3_DIR (
	set EIGEN3_DIR=%EXTERNALS_DIR%\sources\eigen-3.3.9
)

if not defined ALTUMIRA_PLUS_ROOT (
	rem Set ALTUMIRA_PLUS_ROOT to Altumira's installation path so it can be found by CMake
	set ALTUMIRA_PLUS_ROOT=%ADAM_EXTERNALS_DIR%\AltumiraPlus-5.3.4.16

	rem When calling enhancement instances from a thread that is not the main application thread,
	rem one must set the system environmental variable OMP_DYNAMIC=true. Otherwise, image processing results may be unreliable.
	rem OC: is it useful for CUDA processing? Probably not.
	set OMP_DYNAMIC=true

	rem Filename used for encrypted log file generated by Altumira when trace is enabled (if enableVerbose is true)
	set COV_TRACE_FILE=AltumiraPlusLog.dat
)

if not defined BOOST_INCLUDEDIR (
	rem BOOST_INCLUDEDIR is used as input by FindBoost.cmake for only finding headers
	set BOOST_INCLUDEDIR=%ADAM_EXTERNALS_DIR%\Boost-1.78
)

if not defined CMAKE_DIR (
	rem BOOST_INCLUDEDIR is used as input by FindBoost.cmake for only finding headers
	set CMAKE_DIR=%ADAM_EXTERNALS_DIR%\CMake-3.22.2
)

if not defined Torch_DIR (
	set Torch_DIR=%EXTERNALS_DIR%/binaries/torch/libtorch-win-shared-with-deps-1.11.0+cu113/libtorch
)

set PATH=%ALTUMIRA_PLUS_ROOT%\bin;%PATH%
set PATH=%DICOMCONNECT_ROOT%\bin;%PATH%
set PATH=%Qt5_DIR%\bin;%PATH%
set PATH=%VTK_DIR%\bin\Debug;%PATH%
set PATH=%VTK_DIR%\bin\RelWithDebInfo;%PATH%
set PATH=%GDCM_DIR%\bin\Debug;%PATH%
set PATH=%GDCM_DIR%\bin\RelWithDebInfo;%PATH%
set PATH=%CMAKE_DIR%\bin;%PATH%


if not defined GIT_ROOT (
	set GIT_ROOT=C:\Program Files\Git\
)
 